- hosts: all
  tags: build-dep
  tasks:
    - name: Install APT prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - g++
          - make
          - libunwind8-dev
          - liblzma-dev
          - zlib1g-dev
          - libpcap-dev
          - libssl-dev
          - libnuma-dev
          - libgflags-dev
          - libgoogle-glog-dev
          - libgtest-dev
          - python3
          - python3-apt
          - python3-pip
          - pkg-config
        update_cache: yes
      become: true

    - name: Install PIP prerequisite packages
      become: true
      pip:
        name:
          - pyelftools
          - setuptools
        executable: pip3

    - name: Install DPDK build system
      become: true
      pip:
        name:
          - meson
          - ninja
        executable: pip3

    - name: Install gRPC and its requirements (apt)
      apt:
        name:
          - libc-ares-dev
          - libbenchmark-dev
          - libgrpc++-dev
          - libprotobuf-dev
          - protobuf-compiler-grpc
      become: true

    - name: BESS build dependencies installed
      debug:
        msg: "You are now ready to build BESS using build.py"
