# SPDX-FileCopyrightText: 2016-2017, Nefeli Networks, Inc.
# SPDX-FileCopyrightText: 2017, The Regents of the University of California.
# SPDX-FileCopyrightText: 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# Container provisioning for building BESS on Travis CI,
# with various compilers and configurations

# all packages for build are also required here
- name: Install basic build requirements first
  import_playbook: build-dep.yml

- name: Vport kernel module dependencies
  import_playbook: kmod.yml

- hosts: all
  tags: ci
  tasks:
    - name: Install additional compilers for the build container
      apt:
        name:
          - g++
          - clang
          - ccache
        update_cache: yes
      become: true
