# SPDX-FileCopyrightText: 2016-2017, Nefeli Networks, Inc.
# SPDX-FileCopyrightText: 2017, The Regents of the University of California.
# SPDX-FileCopyrightText: 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

- hosts: all
  tags: kmod
  tasks:
    - name: Install list of packages (this step may take a long time)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - build-essential
          - linux-headers-generic
        state: latest
        update_cache: yes
      become: true
