# SPDX-FileCopyrightText: 2016-2017, Nefeli Networks, Inc.
# SPDX-FileCopyrightText: 2017, The Regents of the University of California.
# SPDX-FileCopyrightText: 2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

- hosts: all
  tags: runtime
  tasks:
    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - python3
          - python3-pip
          - libgraph-easy-perl
          - tcpdump
        update_cache: yes
      become: true

    - name: Install list of Python packages
      pip:
        requirements: "{{ playbook_dir }}/requirements-run.txt"
        state: present
        executable: pip3
        extra_args: --require-hashes
      become: true

    - name: Note about C++ runtime libraries
      debug:
        msg: "Note: For runtime environments, ensure protobuf 28.3 and gRPC 1.68 C++ libraries are installed (from Docker image or built separately)"

    - shell: ls -d /sys/devices/system/node/node* | wc -l
      register: num_nodes

    - shell: cat /proc/meminfo | grep Hugepagesize
      register: def_hugepage_size

    - name: Enable huge pages
      ansible.posix.sysctl:
        name: vm.nr_hugepages
        value: "{{ num_nodes.stdout|int * 512 }}"
        sysctl_set: yes
      when: "{{ def_hugepage_size.stdout.find('2048 kB') != -1 }}"
      become: true

    - shell: mount | grep 'type hugetlbfs'
      register: hugetlbfs_mounted
      failed_when: hugetlbfs_mounted.rc == 2

    - name: Mount up /mnt/huge
      mount:
        name: /mnt/huge
        fstype: hugetlbfs
        src: none
        state: mounted
      when: hugetlbfs_mounted.rc == 1
      become: true
