name: clang-format Check
on:
  - pull_request
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        path:
          - check: 'core'
            exclude: '(kmod)' # Exclude "kmod" dir because of different format
          - check: 'protobuf'
            exclude: ''       # Nothing to exclude
          - check: 'sample_plugin/modules'
            exclude: ''       # Nothing to exclude
          - check: 'sample_plugin/protobuf'
            exclude: ''       # Nothing to exclude
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
