# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Intel Corporation

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  check:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
