# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Intel Corporation

name: Close stale issues and PRs

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been stale for 30 days and will be closed in 5 days. Comment to keep it open.'
          stale-pr-message: 'This pull request has been stale for 30 days and will be closed in 5 days. Comment to keep it open.'
          stale-issue-label: 'Stale/issue'
          stale-pr-label: 'Stale/pr'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          days-before-stale: 30
          days-before-close: 5
